### ISSUE TITLE
Import stations not working, cant import two stations to see what i might need to change

### ISSUE THREAD

**Issue by iurirolho** [Ocelot1210/X4_ComplexCalculator#101]
Well I cant import from the station builds I have, pressing the button does nothing, read the manual but somehow I can't get it to import, I will wait for a reply but depending on how long takes to reply I might end up abandoning the tool if no good reply comes out of it.

**Comment by Ocelot1210** [comment]
Please send the following two items.
I will investigate the cause.
- The building plan xml that you tried to import.
- x4.db file. (location is X4_ComplexCalculator\bin\db\x4.db)

**Comment by iurirolho** [comment]
sure thing, db file below
[x4.zip](https://github.com/Ocelot1210/X4_ComplexCalculator/files/7193165/x4.zip)
and also the XML
[constructionplans.zip](https://github.com/Ocelot1210/X4_ComplexCalculator/files/7193166/constructionplans.zip)
both had to be zipped as GitHub does not support the formats native to the files

**Comment by Ocelot1210** [comment]
Thank you for sending the file.
I have found the cause of the problem and report it as follows.

## Cause
The process of importing building plans did not correctly handle modules that cannot be built.
  This problem occurs when the HQ module is included.

## Correspondence
Fixed the process so that unbuildable modules are skipped and imported.
Also, if a headquarters module is found during import, the headquarters in the settings will be checked.


A corresponding version of this phenomenon has been released.
Please use one of the following methods to obtain the latest version of the execution environment and let us know if the problem has been resolved.

- Click "Help(H)" -> "Check Update... " at complex calculator.
- Download the latest version [here](https://github.com/Ocelot1210/X4_ComplexCalculator/releases)

Thank you.

**Comment by iurirolho** [comment]
ok going to update, thx for fixing that bug so quick
