### ISSUE TITLE
The given key 'hull_test' was not present in the dictionary.

### ISSUE THREAD

**Issue by mycumycu** [Ocelot1210/X4_ComplexCalculator#117]
After using import DB function (data exporter) - got "Data export completed message".
And then "The given key 'hull_test' was not present in the dictionary." error occures:
https://i.imgur.com/ZO83x5Z.png

- OS: Windows 10
- Language Polish
- X4 v. 4.2b2
- X4_ComplexCalculator v 3.0.8

**Comment by Ocelot1210** [comment]
Could you please let me know what mods you have installed?

**Comment by mycumycu** [comment]
If you need the mod list to find 'hull_test' - it comes from this mod as far as I can see:
https://steamcommunity.com/sharedfiles/filedetails/?id=2657805078

I currently have it in the mod list, but it is not active.

Made a test and removed this mod from /extensions folder - X4_ComplexCalculator works fine.

As far as I can see X4_CC takes into account all mods when building DB - active and disabled.
E.g. I have X4 Economy Overhaul, which I don't use in current playthrough, but keep it on a list because probably will play with it on next playthrough. 
So it will affect X4_ComplexCalculator output (because it changes station modules params) even if it's disabled?
Maybe X4_ComplexCalculator should get data only just from active mods?

**Comment by Ocelot1210** [comment]
> If you need the mod list to find 'hull_test' - it comes from this mod as far as I can see:
> https://steamcommunity.com/sharedfiles/filedetails/?id=2657805078

Thank you for the information. I have confirmed that the problem is reproduced.  
<br/>

> As far as I can see X4_CC takes into account all mods when building DB - active and disabled.
> So it will affect X4_ComplexCalculator output (because it changes station modules params) even if it's disabled?

It was as you perceived it.
X4_CC was getting the data of the Mod even if the Mod was disabled.  
<br/>


> Maybe X4_ComplexCalculator should get data only just from active mods?

That's right.
If a Mod is disabled, X4_CC should not load that mod.  
<br/>

---
A version has been released that fixes this issue.
Please use one of the following methods to obtain the latest version of the execution environment and let us know if the problem has been resolved.

- Click "Help(H)" -> "Check Update... " at complex calculator.
- Download the latest version [here](https://github.com/Ocelot1210/X4_ComplexCalculator/releases)

Thank you.

**Comment by mycumycu** [comment]
That was fast!
Issue has been resolved and disabled mods are not affecting data.

Thank you! :heart:
