### ISSUE TITLE
Error when Exporting DB, my first time using this calculator.

### ISSUE THREAD

**Issue by shadowfax13th** [Ocelot1210/X4_ComplexCalculator#131]
I'm trying to use your calculator for the first time, and the shortcut that comes with when extracted is bad.
Also, when exporting initially I got an error.

[X4_ComplexCalculator_CrashReport.txt](https://github.com/Ocelot1210/X4_ComplexCalculator/files/8353610/X4_ComplexCalculator_CrashReport.txt)

It is the latest STEAM version of the game, post 5.0 update with all three dlc's. And many mods.... many many mods.

**Comment by Ocelot1210** [comment]
Thank you for reporting the problem.
I will investigate the cause.

**Comment by shadowfax13th** [comment]
thank you for your time, and the fast reply

**Comment by Ocelot1210** [comment]
I have confirmed that data is exported successfully in an environment similar to the one you reported.
(I was not able to download some of the mods, so the environment I checked is not entirely your environment.)

I have found the cause of the problem and report it as follows.

## Cause
The main cause of this issue was the inability to correctly handle path strings of an unintended format contained in certain mods.

## Correspondence
I fixed this issue by correctly handling unintended forms of path strings.

---
A version that fixes this issue has been released.
Download the latest version [here](https://github.com/Ocelot1210/X4_ComplexCalculator/releases) and let me know if the problem has been resolved.

**Comment by shadowfax13th** [comment]
Sorry for the really late response, but thank you very much for the fix. Dloading and attempting it today.

**Comment by shadowfax13th** [comment]
Ok, verified working and like I said this is my first time using your calculator... this rocks! Thankx so much
