### ISSUE TITLE
Failed to resolve mod depedencies

### ISSUE THREAD

**Issue by mycumycu** [Ocelot1210/X4_ComplexCalculator#178]
Hi, I've updated X4_ComplexCalculator to latest version and while running data exporter, I got:

![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/33801919/60198333-809d-42a9-851d-b9c180b6b470)

is it possible to see which mod is causing trouble for exporter?

**Comment by Ocelot1210** [comment]
Thank you for contacting me.
I apologize for the delay in responding to you.

The current calculator does not allow us to see which mod is causing the problem.
I have created a function to display the mods that are causing the problem as shown in the image below.
![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/16898663/ee7ac5e4-f3ab-49b3-b927-332d43c6d1d6)

Please download the execution environment from the following URL and let me know if the problem is resolved.
https://github.com/Ocelot1210/X4_ComplexCalculator/releases/tag/v3.1.6

[Note]
The following is a pre-release, so the automatic updating function of the calculator cannot be used. 
Once I confirm that the problem is resolved, I would like to make it an official release so that other users can be automatically updated.

**Comment by mycumycu** [comment]
Now it shows that mod list:  

![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/33801919/fe1f0812-62f1-4b9f-87b6-236bc6a75cf6)

Strangely - the first one (Valkyrie) is disabled - doesn't the data exporter take mod enabled/disabled 'status'  into account?

But even if I remove this disabled - it still fails, even all listed mods are correct:

![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/33801919/3f8a2477-1349-4776-a877-28628f827d8c)

Maybe the issue is with some disabled mod that the exporter tries to read?

**Comment by Ocelot1210** [comment]
The exporter is processing the disabled mods so that they are not read.
However, there is a possibility that the exporter is unintentionally reading disabled mods due to some issue.
Or, the dependency resolution method used by the exporter may be inappropriate.

I would like to confirm the issue, so please let us know the status of the Mods that can be displayed from the X4 start menu. (as shown in the image below)

![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/16898663/fd984b58-bbfa-4406-a69f-519a200ba4d6)

**Comment by mycumycu** [comment]
TBH it might be hard to track as there are 'few' of them... ;)

![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/33801919/624679b6-22e2-47d9-89d7-869327ddb5ba)
![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/33801919/74c49883-23e9-4d05-944e-b6f97fdd73a6)
![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/33801919/4405b431-2c55-4a4c-80e5-cc78a3529517)
![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/33801919/8097d379-c164-403a-8653-e4daf55de580)
![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/33801919/5245182e-095c-4308-aadc-18c113732c24)

**Comment by Ocelot1210** [comment]
Thank you for contacting me.
Unfortunately, I was unable to reproduce the problem. I will continue to investigate.
In some cases I may need further assistance from you, and I thank you in advance for your cooperation.

**Comment by mycumycu** [comment]
No problem, thanks for putting your time into it.
I'll also make some testing on my side when time allows.

**Comment by Ocelot1210** [comment]
When a Mod's dependency resolution fails, it is now displayed as shown in the image below instead of in a message box.
I would appreciate it if you could check how it is displayed and contact me.
The latest application can be downloaded [here (v3.1.6-b2)](https://github.com/Ocelot1210/X4_ComplexCalculator/releases/tag/v3.1.6-b2).

![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/16898663/8a693793-80ed-4707-b63d-ab8e4f233196)

**Comment by mycumycu** [comment]
I've dopwnloaded v3.1.6-b2, but still get the same output screen:
https://i.imgur.com/upkC1WH.png

**Comment by Ocelot1210** [comment]
The application I published was out of date. I apologize for the inconvenience.
Please check back as I have updated it again.
The download link is [here](https://github.com/Ocelot1210/X4_ComplexCalculator/releases/tag/v3.1.6-b2).

**Comment by mycumycu** [comment]
Thanks, now the output is different.
All those mods exist, but looks like somehow it can't see them.

![image](https://github.com/Ocelot1210/X4_ComplexCalculator/assets/33801919/84433887-bdd1-4036-b05b-1fc22ca07871)

**Comment by mycumycu** [comment]
So it looks like problem with folder paths - how does it build the dependency tree - especially 'folder name' values?

**Comment by mycumycu** [comment]
Oh, nice and detailed explantion.
Your'e right about the issue's source - I have two profiles (one I keep for vanilla playthrough - let's call it profile A, second one is mod based - profile B).
So the source of the issue was the fact that whenever user installs a new mod for profile B - profile A has this mod automatically added and enabled - basically the new mod is being added to all profiles.
So I was in a situation when profile A had also enabled newer mods from profile B - without dependencies, that were disabled.

As you said - disabling profile A for the time of generating data for Complex Calculator fixed the issue.
I can use this great tool again. 

Thanks!
