### ISSUE TITLE
Language select empty

### ISSUE THREAD

**Issue by maritz** [Ocelot1210/X4_ComplexCalculator#26]
The language select box has no entries to select, thus I cannot import the DB.

![image](https://user-images.githubusercontent.com/159633/90098481-a4bd5500-dd38-11ea-8245-07e24173edb7.png)

Tried v1.2.3, v1.2.2, v1.2.1 and v1.0.0. All the same.

**Comment by Ocelot1210** [comment]
The language list is empty because exporter failed to get a list of languages available in X4.
Please try the following steps.

### 1. Check input folder path.
Please make sure you have selected the correct destination folder for the X4 installation.  
The correct folder path is the parent folder path of "X4.exe".

![no title](https://user-images.githubusercontent.com/16898663/90119694-d8c66380-dd94-11ea-9651-941c094647af.jpg)
NOTE: Please replace with "￥" to "\\".  
I'm using the Japanese environment, so "\\" is shown as "￥".
<br>

### 2. Disable mods. (if using mods)
- When using a mod, please rename the extensions folder and check the operation again with the mod not recognized.  
If work succeed when renamed extensions folder, please tell me your installed mods.
<br>

If you continue to experience problems, please contact me again.

Thank you.

**Comment by maritz** [comment]
Huh, after renaming it to "aextensions", it still didn't work. Looking at some random code, I found a questionable regexp that looks for folders that contain "extensions" for some reason, instead of completely matching the entire name. After scrambling the name completely it loaded the language list and import worked.

Here are my currently used mod directories:

```apologizeforattack/
'Average Prices Suffixes'/
Better_tractor_beam/
BetterScanColors/
BK_TurretBehavior/
data_leak_modifications/
DeadAirDynamicWars-master/
ego_dlc_split/
escape_teleport/
faction_fix_pack/
faction_fix_pack_catchup/
faction_fix_pack_econ_ai/
faction_fix_pack_econ_bal/
G_Work_Around/
infocenter/
JP_AnotherExplorerV2/
JP_DataVaultExplorer/
JP_MultiRename/
kuertee_signal_leak_hunter_increasing_range/
kuertee_station_scanner/
kuertee_ui_active_mission_button/
kuertee_ui_reset_mouse_on_menu_close/
learningallthethings/
Legacy_Music/
mej_disable_encounters/
mules_and_warehouses_extended/
No_Battle_Music/
NoMoreNotificationsSound/
NoSuperHighway/
phq-warp/
RightClickAPI/
SatNetwork/
shib_paythebuilder/
sn_asteroid_fade/
sn_better_target_monitor/
sn_extra_game_options/
sn_mod_support_apis/
sn_reduce_fog/
'Spacesuit thrust upgrade'/
spherical_long_range_scan/
TaterTrader-master/
trade_buy_notification/
Unique_Datavault_Pings/
vro/
vroicons-stable/
vxLegalInventory/
x4_fireandsmoke/
``` 

Why would the mod directories prevent this though?

**Comment by Ocelot1210** [comment]
> Huh, after renaming it to "aextensions", it still didn't work.  

I'm not sure why renaming the "extensions" folder to the "aextensions" folder doesn't work.
However, it's probably because the process that updates the language list is not called when the same folder as the last time is specified.
<br>


> Why would the mod directories prevent this though?

The data extraction process tries to create a language list including in the mod folder.
At that time, if some error occurs, it will assume that the folder other than the installation folder of X4 was selected and the language list will be empty.
In this case, there was an unexpected pattern when loading the "content.xml" in the Mod folder, so it was treated as an error and the language list was empty.


### Cause
- Due to an unexpected pattern when loading "content.xml" into the mod folder, it was treated as an error and the language list was empty.
    - It failed to take into account the case where the xml declaration and other tags are on the same line.

#### example
The XML declaration was assumed to be in the first line by itself.
```
<?xml version="1.0" encoding="utf-8"?>
<content id="foo" ... />
```

However, the "content.xml" in "kuertee_ui_reset_mouse_on_menu_close" looks like this, and the rest of the xml declaration was unintentionally skipped.
```
<?xml version="1.0" encoding="utf-8"?><content id="kuerteeUIResetMouseOnMenuClose"
	name="kuertee UI: Reset mouse on menu close"
	:
```


### Correspondence
Fixed a process to ensure only XML declarations are skipped.


I will be releasing a version that fixes this bug soon.
We'll let you know when it's released.


Thank you.

**Comment by maritz** [comment]
I manually fixed all the content.xml files as indicated and it now updates the DB properly! 👍

**Comment by Ocelot1210** [comment]
I have released a version that addresses this issue.  
Please download the latest execution environment [here](https://github.com/Ocelot1210/X4_ComplexCalculator/releases).

If you continue to experience problems, please contact me again.

Thank you for contacting me with the bug.
