### ISSUE TITLE
input string was not in a correct format

### ISSUE THREAD

**Issue by mycumycu** [Ocelot1210/X4_ComplexCalculator#5]
Hi,
an error occures when exporting data from X4:
[https://i.imgur.com/sc96uW3.png](https://i.imgur.com/sc96uW3.png)

Tried both releases.

**Comment by proudust** [comment]
@mycumycu Please tell me which mod you have installed.

**Comment by mycumycu** [comment]
There are a few of them... ;)
https://i.imgur.com/vg01DJH.png

**Comment by Ocelot1210** [comment]
Sorry, we were unable to reproduce the phenomenon here.  

However, I fixed it so that the data extraction succeeds in the environment where the mod you contacted is installed. It should probably work in your environment as well.  

If the data extraction still fails using the [latest release](https://github.com/Ocelot1210/X4_ComplexCalculator/releases), please contact us again.

Thank you for your patience.

**Comment by mycumycu** [comment]
I can imagine that it might be hard to track with mods on top.
Recently started a holiday so I don't have currently access to my computer with X4 installed - but will try latest release in two weeks.

**Comment by mycumycu** [comment]
Hi, tried latest release and got this output:

[X4_ComplexCalculator_CrashReport.txt](https://github.com/Ocelot1210/X4_ComplexCalculator/files/5050475/X4_ComplexCalculator_CrashReport.txt)

**Comment by Ocelot1210** [comment]
About the following mods, I found out that the version of the mod you and I are using is different.
Please confirm the execution after updating the mod.

1. Faction Enhancer - War Module
1. Faction Enhancer - Catchup Module
1. Faction Enhancer - Econ AI Module
1. Faction Enhancer - Econ Balance Module
1. Cheat Menu
<br>

Also, I could not get the mods because I could not find the following mod distribution sites.
When data extraction fails even after updating the above mod, please exclude the following mods from X4 and confirm execution again.
1. Less Stardust
<br>

Thank you.

**Comment by mycumycu** [comment]
Ok, so I've updated Faction Enhancer mod family to latest version and removed Cheat Menu mod.
Less Stardust is a (not published) custom simple mod which replaces two values. I've excluded it.
Take a look at generated output:

[X4_ComplexCalculator_CrashReport.txt](https://github.com/Ocelot1210/X4_ComplexCalculator/files/5051110/X4_ComplexCalculator_CrashReport.txt)

Thanks.

**Comment by mycumycu** [comment]
Ok, I'll try to find the culprit when time allows.
Do I need to uncheck mod in game or simply remove mod's folder from extensions directory before extracting?

**Comment by Ocelot1210** [comment]
Please remove mod's folder from extensions directory.

**Comment by mycumycu** [comment]
Tried latest release (1.3.1) and got:

---
> Exception information
> 
> 
> ■ Type :
> LibX4.Xml.XmlFormatException
> 
> ■ Message :
> XML format is invalid.
> Input: 1.5
> Parent: 
> `<production time="1.5" amount="1" method="default" name="{20206,101}">
>     <primary>
>     <ware ware="energycells" amount="15" />
>     <ware ware="missilecomponents" amount="4" />
>   </primary>
> </production>`

> ■ StackTrace :
>    at LibX4.Xml.XAttributeExtension.GetDouble(XAttribute attr)
>    at X4_DataExporterWPF.Export.EquipmentProductionExporter.GetRecords()+MoveNext()
>    at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 535
>    at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 441
>    at X4_DataExporterWPF.Export.EquipmentProductionExporter.Export(IDbConnection connection)
>    at X4_DataExporterWPF.DataExportWindow.DataExportModel.Export(IProgress`1 progless, String inDirPath, String outFilePath, LangComboboxItem language)

---

Also I've tried with removed entire /Extensions folder (created empty one), but got same output.

**Comment by Ocelot1210** [comment]
Thank you for contacting me.
I have found the cause of this problem and would like to inform you as follows.

### Cause
This was due to the fact that the culture used to parse the values varies from user to user.
<br>

#### example
When parsing the string "1.5", it succeeds or fails depending on the culture, as shown below.
| No | Culture | Result |
| --:  | --- | --- |
| 1 | en-US | 1.5 |
| 2 | ja-JP | 1.5 |
| 3 | fr-FR | **FormatException** |

<br>

### Correspondence
Fixes the culture used when parsing values.

<br>

A corresponding version of this phenomenon has been released.
Please download the latest version [here](https://github.com/Ocelot1210/X4_ComplexCalculator/releases).

If you continue to experience problems, please contact me again.
Thank you.

**Comment by mycumycu** [comment]
Yes, that was the reason. 
Everything works great now 👍 

Thanks for your time and dedication.
